name: canfinity
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.5
  http: ^1.3.0
  sqflite: ^2.3.0
  path_provider: ^2.0.15
  path: ^1.8.3
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.2.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/holding_hands_cancer.jpg
